name: "Build Wheel"
description: "Build wheel for ML repos e.g. sparseml, compressed-tensors"

inputs:
    dev:
      description: 'If the build is a dev build'
      required: false
      default: false
    release:
      description: 'If the build is a release build'
      required: false
      default: false
    name:
      description: 'Name to append to the wheel'
      required: false
    venv:
      description: 'path of virtualenv if using it'
      required: false
outputs:
    whlname:
      description: 'wheel filename'
      value: ${{ steps.build.outputs.whlname }}
    tarname:
      description: 'tar.gz filename'
      value: ${{ steps.build.outputs.tarname }}
    status:
      description: 'status of wheel build'
      value: ${{ steps.build.outputs.status }}

# can we just pass in build args instead of updating the variables in version.py?
runs:
  using: "composite"
  steps:
    - name: build
      id: build
      shell: bash
      run:  |
            if [[ ! -z "${{ inputs.venv }}" ]]; then
                source ${{ inputs.venv }}/bin/activate
            fi
            pip install wheel
            name="${{ inputs.name }}"
            ver_file=$(find . -type f -name "version.py")
            if ${{ inputs.release }}; then
              sed -i 's/is_release = False/is_release = True/g' ${ver_file}
              sed -i 's/build_type = "dev"/build_type = "release"/g' ${ver_file}
            elif ${{ inputs.dev }}; then
              sed -i 's/is_dev = False/is_dev = True/g' ${ver_file}
              sed -i 's/dev_number = None/dev_number = '"$name"'/g' ${ver_file}
            else
                sed -i 's/build_type = "dev"/build_type = "nightly"/g' ${ver_file}
            fi
            status=0
            makefile_path=$(find . -type f -name "Makefile")
            cd $(dirname ${makefile_path})
            make -B build || status=$?
            ls dist/; mkdir build-results
            echo "
            <testsuites>
                <testsuite errors=\"$status\" failures=\"$status\" name=\"build\" skipped=\"0\" tests=\"1\">
                    <testcase classname=\"build\"/>
                </testsuite>
            </testsuites>" > build-results/result.xml
            echo "=========== Build log ==========="
            echo "$status"
            echo "whlname=$(find dist -name '*.whl' -exec basename {} \;)" >> "$GITHUB_OUTPUT"
            echo "tarname=$(find dist -name '*.tar.gz' -exec basename {} \;)" >> "$GITHUB_OUTPUT"
            echo "status=${status}" >> "$GITHUB_OUTPUT"
            exit ${status}
