---
name: Test self-contained Testmo actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: neuralmagic/nm-actions/actions/testmo-run-create@self-contained-testmo-actions-test
        with:
          testmo_url: https://neuralmagic.testmo.net
          testmo_token: INVALID-TOKEN
          source: test-actions
          project_id: eleventy-one
          run_name: kwyjibo
